###################
# ENV VARS:
# - FULL_NAME
# - EMAIL
# - PAT (generated at Personal Access Tokens - with workflow access checked)
###################

name: Check for new releases

# Triggers: manually or by a scheduled time
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Optional: Specify the version to set'
        required: false
  schedule:
    - cron: "0 0 */1 * *"  # Runs at midnight every day

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Fetch or set release version
        id: set-version
        run: |
          version=${{ github.event.inputs.version }}
          if [ -z "$version" ]; then
            echo "Fetching latest version from n8n repository"
            version=$(curl -sL https://raw.githubusercontent.com/n8n-io/n8n/master/package.json | jq -r ".version")
          fi
          echo $version > release-versions/n8n-latest.txt
          echo "::set-output name=version::$version"

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.set-version.outputs.version != ''
        with:
          commit_message: New auto release v${{steps.set-version.outputs.version}}
